services:
  db:
    image: postgres:14
    container_name: realestate_db
    env_file:
      - backend/.env.production
    volumes:
      - postgres_data_realestate:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: realestate_backend
    env_file:
      - backend/.env.production
    environment:
      - DJANGO_ENV=production
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      - db
    ports:
      - "8001:8000"        

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realestate_nginx_proxy
    volumes:
      - ./nginx_realestate/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/media:/media:ro
      - static_volume:/static:ro
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data_realestate:
  static_volume: