version: '3.8'

services:
  db:
    image: postgres:14
    container_name: realestate_db
    env_file:
      - backend/.env.prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_realestate:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: realestate_backend
    env_file:
      - backend/.env.prod
    environment:
      - DJANGO_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: ["sh", "./entrypoint.sh"]
    ports:
      - "8000:8000"        

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: realestate_nginx_proxy
    volumes:
      - ./nginx_realestate/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/www/realestate/backend/media:/media:ro
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data_realestate: