# Generated by Django 5.0.3 on 2024-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='name',
        ),
        migrations.AddField(
            model_name='realtor',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='realtor',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
