# Generated by Django 5.0.3 on 2024-06-08 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_list_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='list_date',
        ),
        migrations.AddField(
            model_name='listing',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
