# Generated by Django 5.0.3 on 2024-06-08 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_list_date_listing_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='publish_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
