# Generated by Django 5.1.7 on 2025-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Appartment')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('Buy', 'For Sale'), ('Rent', 'For Rent')], default='Buy', max_length=50),
        ),
    ]
