# Generated by Django 5.0.3 on 2024-06-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('realtor', 'Realtor')], default='user', max_length=50),
        ),
    ]
